language: php

php:
  - 7.1

before_install:
  - openssl aes-256-cbc -K $encrypted_52f1e6b634db_key -iv $encrypted_52f1e6b634db_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - echo "the world"

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/hentai && git pull origin master' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/hentai && composer install' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'service supervisord restart'
    on:
      branch: master
